version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - staticcheck
  settings:
    misspell: # https://golangci-lint.run/usage/linters/#misspell
      ignore-rules:
        - "Criterias"
    revive: # https://golangci-lint.run/usage/linters/#revive
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: empty-block
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: indent-error-flow
        - name: package-comments
          disabled: true
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: superfluous-else
        - name: time-naming
        - name: unexported-return
        - name: unreachable-code
        - name: unused-parameter
        - name: var-declaration
        - name: var-naming
          arguments:
            - [] # AllowList
            - [] # DenyList
            - - skip-package-name-checks: true
    staticcheck: # https://golangci-lint.run/usage/linters/#staticcheck
      checks:
        - all
        - -ST1000 # at least one file in a package should have a package comment
        - -ST1005 # error strings should not be capitalized
  exclusions:
    rules:
      - source: "defer .+\\.Close\\(\\)"
        linters:
          - errcheck
      - source: "defer os.Remove\\(.+\\)"
        linters:
          - errcheck

formatters:
  enable:
    - goimports

run:
  timeout: 10m
