name: golang-ci

linters-settings:
  errcheck:
    #exclude: /path/to/file.txt

linters:
  disable-all: true
  enable:
    - goimports
    - revive
    - govet
    - misspell
    - errcheck
    - staticcheck
    - prealloc
    - ineffassign
