project_name: vuls
env:
  - GO111MODULE=on
release:
  github:
    owner: future-architect
    name: vuls
builds:
- id: vuls
  goos:
  - linux
  goarch:
  - amd64
  main: ./cmd/vuls/main.go
  flags:
  - -a
  ldflags: 
  - -s -w -X github.com/future-architect/vuls/config.Version={{.Version}} -X github.com/future-architect/vuls/config.Revision={{.Commit}}-{{ .CommitDate }}
  binary: vuls

- id: vuls-scanner
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  main: ./cmd/scanner/main.go
  flags:
  - -a
  tags:
  - scanner
  ldflags: 
  - -s -w -X github.com/future-architect/vuls/config.Version={{.Version}} -X github.com/future-architect/vuls/config.Revision={{.Commit}}-{{ .CommitDate }}
  binary: vuls-scanner

- id: trivy-to-vuls
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  tags:
  - scanner
  main: ./contrib/trivy/cmd/main.go
  binary: trivy-to-vuls

- id: future-vuls
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  flags:
  - -a
  tags:
  - scanner
  main: ./contrib/future-vuls/cmd/main.go
  binary: future-vuls

archives:

- id: vuls
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  builds:
  - vuls
  format: tar.gz
  files:
  - LICENSE
  - README*
  - CHANGELOG.md

- id: vuls-scanner
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  builds:
  - vuls-scanner
  format: tar.gz
  files:
  - LICENSE
  - README*
  - CHANGELOG.md

- id: trivy-to-vuls
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  builds:
  - trivy-to-vuls
  format: tar.gz
  files:
  - LICENSE
  - README*
  - CHANGELOG.md

- id: future-vuls
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  builds:
  - future-vuls
  format: tar.gz
  files:
  - LICENSE
  - README*
  - CHANGELOG.md
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
