version: 2
project_name: vuls
release:
  github:
    owner: future-architect
    name: vuls
builds:
- id: vuls
  env:
  - CGO_ENABLED=0
  - GOEXPERIMENT=jsonv2
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
  main: ./cmd/vuls/main.go
  flags:
  - -a
  - -trimpath
  ldflags: 
  - -s -w -X github.com/future-architect/vuls/config.Version={{.Version}} -X github.com/future-architect/vuls/config.Revision={{.Commit}}-{{ .CommitDate }}
  binary: vuls

- id: vuls-scanner
  env:
  - CGO_ENABLED=0
  - GOEXPERIMENT=jsonv2
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
  main: ./cmd/scanner/main.go
  tags:
  - scanner
  flags:
  - -a
  - -trimpath
  ldflags: 
  - -s -w -X github.com/future-architect/vuls/config.Version={{.Version}} -X github.com/future-architect/vuls/config.Revision={{.Commit}}-{{ .CommitDate }}
  binary: vuls-scanner

- id: trivy-to-vuls
  env:
  - CGO_ENABLED=0
  - GOEXPERIMENT=jsonv2
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
  main: ./contrib/trivy/cmd/main.go
  tags:
  - scanner
  flags:
  - -a
  - -trimpath
  ldflags: 
  - -s -w -X github.com/future-architect/vuls/config.Version={{.Version}} -X github.com/future-architect/vuls/config.Revision={{.Commit}}-{{ .CommitDate }}
  binary: trivy-to-vuls

- id: future-vuls
  env:
  - CGO_ENABLED=0
  - GOEXPERIMENT=jsonv2
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
  tags:
  - scanner
  flags:
  - -a
  - -trimpath
  ldflags: 
  - -s -w -X github.com/future-architect/vuls/config.Version={{.Version}} -X github.com/future-architect/vuls/config.Revision={{.Commit}}-{{ .CommitDate }}
  main: ./contrib/future-vuls/cmd/main.go
  binary: future-vuls

- id: snmp2cpe
  env:
  - CGO_ENABLED=0
  - GOEXPERIMENT=jsonv2
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
  tags:
  - scanner
  flags:
  - -a
  - -trimpath
  ldflags: 
  - -s -w -X github.com/future-architect/vuls/config.Version={{.Version}} -X github.com/future-architect/vuls/config.Revision={{.Commit}}-{{ .CommitDate }}
  main: ./contrib/snmp2cpe/cmd/main.go
  binary: snmp2cpe

archives:

- id: vuls
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  ids:
  - vuls
  formats: ['tar.gz']
  files:
  - LICENSE
  - README*
  - CHANGELOG.md

- id: vuls-scanner
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  ids:
  - vuls-scanner
  formats: ['tar.gz']
  files:
  - LICENSE
  - README*
  - CHANGELOG.md

- id: trivy-to-vuls
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  ids:
  - trivy-to-vuls
  formats: ['tar.gz']
  files:
  - LICENSE
  - README*
  - CHANGELOG.md

- id: future-vuls
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  ids:
  - future-vuls
  formats: ['tar.gz']
  files:
  - LICENSE
  - README*
  - CHANGELOG.md

- id: snmp2cpe
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  ids:
  - snmp2cpe
  formats: ['tar.gz']
  files:
  - LICENSE
  - README*
  - CHANGELOG.md

snapshot:
  version_template: SNAPSHOT-{{ .Commit }}

signs:
- cmd: cosign
  env:
  - COSIGN_EXPERIMENTAL=1
  signature: "${artifact}.sigstore.json"
  args:
  - "sign-blob"
  - "--bundle=${signature}"
  - "${artifact}"
  - "--yes"
  artifacts: all
  output: true
