project_name: vuls
env:
  - GO111MODULE=on
release:
  github:
    owner: future-architect
    name: vuls
builds:
- goos:
  - linux
  goarch:
  - amd64
  main: .
  flags:
      - -a
  ldflags: -s -w -X main.version={{.Version}} -X main.revision={{.Commit}} 
  binary: vuls
archives:
- name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  files:
  - LICENSE
  - NOTICE
  - README*
  - CHANGELOG.md
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
