build:
  nodes:
    my-first-test:
      - command 'pwd'
  root_path: './'
  resources:
    cpus: 1
  environment:
    timezone:             UTC
    variables:
      GO111MODULE: on
    go:                       "go1.11.4"