["192.168.0.6"]
  ip = "192.168.0.6"
  server_name = "aaa4"
  uuid = "dcec921b-a1d5-d532-03a3-6928082e9556"
  cpe_uris = ["cpe:2.3:h:fortinet:fortigate-50e:-:*:*:*:*:*:*:*", "cpe:2.3:o:fortinet:fortios:5.4.6:*:*:*:*:*:*:*"]
  fvuls_sync = true

["192.168.0.7"]
  ip = "192.168.0.7"
  server_name = "bbb2"
  uuid = "7ac4a11e-a300-6c36-4e3b-80433135a9da"
  cpe_uris = ["cpe:2.3:h:fortinet:fortigate-50e:-:*:*:*:*:*:*:*", "cpe:2.3:o:fortinet:fortios:5.4.6:*:*:*:*:*:*:*"]
  fvuls_sync = true
