package cwe

// CweDictJa is the Cwe dictionary
var CweDictJa = map[string]Cwe{
	"1": {
		CweID:               "1",
		Name:                "ロケーション(CWE-1)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"1004": {
		CweID:               "1004",
		Name:                "HttpOnly 属性のない重要な Cookie(CWE-1004)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"1021": {
		CweID:               "1021",
		Name:                "レンダリングされたユーザインターフェースレイヤまたはフレームの不適切な制限(CWE-1021)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"1076": {
		CweID:               "1076",
		Name:                "期待した規則への不十分な順守(CWE-1076)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"1104": {
		CweID:               "1104",
		Name:                "メンテナンスされていないサードパーティ製コンポーネントの使用(CWE-1104)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"112": {
		CweID:               "112",
		Name:                "XML 検証の欠如(CWE-112)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"113": {
		CweID:               "113",
		Name:                "HTTP レスポンスの分割(CWE-113)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"115": {
		CweID:               "115",
		Name:                "入力の誤った解釈(CWE-115)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"116": {
		CweID:               "116",
		Name:                "不適切なエンコード、または出力のエスケープ(CWE-116)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"117": {
		CweID:               "117",
		Name:                "不適切なログ出力の無効化(CWE-117)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"118": {
		CweID:               "118",
		Name:                "インデックス化が可能なリソースの不適切なアクセス (範囲エラー)(CWE-118)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"1187": {
		CweID:               "1187",
		Name:                "初期化されていないリソースの使用(CWE-1187)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"1188": {
		CweID:               "1188",
		Name:                "リソースの安全ではないデフォルト値への初期化(CWE-1188)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"119": {
		CweID:               "119",
		Name:                "バッファエラー(CWE-119)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"120": {
		CweID:               "120",
		Name:                "古典的バッファオーバーフロー(CWE-120)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"121": {
		CweID:               "121",
		Name:                "スタックベースのバッファオーバーフロー(CWE-121)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"122": {
		CweID:               "122",
		Name:                "ヒープベースのバッファオーバーフロー(CWE-122)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"123": {
		CweID:               "123",
		Name:                "任意の場所に任意の値を書き込み可能な状態(CWE-123)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"1236": {
		CweID:               "1236",
		Name:                "CSV ファイル内の数式要素の不適切な中和(CWE-1236)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"124": {
		CweID:               "124",
		Name:                "バッファアンダーフロー (CWE-124)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"125": {
		CweID:               "125",
		Name:                "境界外読み取り(CWE-125)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"126": {
		CweID:               "126",
		Name:                "バッファオーバーリード(CWE-126)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"1278": {
		CweID:               "1278",
		Name:                "集積回路（IC）イメージング技術を用いたハードウェアリバースエンジニアリングへの保護の欠如(CWE-1278)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"1284": {
		CweID:               "1284",
		Name:                "入力で指定された数量の不適切な検証(CWE-1284)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"1286": {
		CweID:               "1286",
		Name:                "入力の構文的正当性の不適切な検証(CWE-1286)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"129": {
		CweID:               "129",
		Name:                "配列インデックスの不適切な検証(CWE-129)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"130": {
		CweID:               "130",
		Name:                "レングスパラメーターの不整合による不適切な処理(CWE-130)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"131": {
		CweID:               "131",
		Name:                "バッファサイズの計算の誤り(CWE-131)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"1321": {
		CweID:               "1321",
		Name:                "オブジェクトプロトタイプ属性の不適切に制御された変更 (プロトタイプの汚染)(CWE-1321)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"134": {
		CweID:               "134",
		Name:                "書式文字列の問題(CWE-134)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"15": {
		CweID:               "15",
		Name:                "システム構成または設定の外部制御(CWE-15)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"150": {
		CweID:               "150",
		Name:                "エスケープ、メタ、またはコントロールシーケンスの不適切な無効化(CWE-150)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"158": {
		CweID:               "158",
		Name:                "NULL バイトまたは NULL キャラクタの不適切な無害化(CWE-158)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"16": {
		CweID:               "16",
		Name:                "環境設定(CWE-16)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"17": {
		CweID:               "17",
		Name:                "コード(CWE-17)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"170": {
		CweID:               "170",
		Name:                "不適切な NULL による終了(CWE-170)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"171": {
		CweID:               "171",
		Name:                "クレンジング、正規化、および比較エラー(CWE-171)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"172": {
		CweID:               "172",
		Name:                "エンコーディングエラー(CWE-172)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"178": {
		CweID:               "178",
		Name:                "大文字と小文字の区別の不適切な処理(CWE-178)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"18": {
		CweID:               "18",
		Name:                "ソースコード(CWE-18)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"184": {
		CweID:               "184",
		Name:                "不完全なブラックリスト(CWE-184)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"185": {
		CweID:               "185",
		Name:                "不正な正規表現(CWE-185)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"189": {
		CweID:               "189",
		Name:                "数値処理の問題(CWE-189)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"19": {
		CweID:               "19",
		Name:                "データ処理(CWE-19)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"190": {
		CweID:               "190",
		Name:                "整数オーバーフローまたはラップアラウンド(CWE-190)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"191": {
		CweID:               "191",
		Name:                "整数アンダーフロー(CWE-191)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"193": {
		CweID:               "193",
		Name:                "境界条件の判定(CWE-193)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"194": {
		CweID:               "194",
		Name:                "予期しない符号拡張(CWE-194)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"197": {
		CweID:               "197",
		Name:                "数値打ち切り誤差(CWE-197)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"199": {
		CweID:               "199",
		Name:                "情報管理の問題(CWE-199)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"20": {
		CweID:               "20",
		Name:                "不適切な入力確認(CWE-20)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"200": {
		CweID:               "200",
		Name:                "情報漏えい(CWE-200)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"201": {
		CweID:               "201",
		Name:                "送信データへの重要な情報の挿入(CWE-201)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"202": {
		CweID:               "202",
		Name:                "データクエリからの重要な情報の漏えい(CWE-202)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"2020-7809 | Estsoft ALSong DOM-Based XSS Vulnerability": {
		CweID:               "2020-7809 | Estsoft ALSong DOM-Based XSS Vulnerability",
		Name:                "",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"203": {
		CweID:               "203",
		Name:                "観測可能な不一致(CWE-203)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"204": {
		CweID:               "204",
		Name:                "リクエストに対するレスポンス内容の違いに起因する情報漏えい(CWE-204)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"208": {
		CweID:               "208",
		Name:                "タイミングの違いに起因する情報漏えい(CWE-208)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"209": {
		CweID:               "209",
		Name:                "エラーメッセージによる情報漏えい(CWE-209)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"21": {
		CweID:               "21",
		Name:                "パス名トラバーサルおよび同値エラー(CWE-21)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"212": {
		CweID:               "212",
		Name:                "保存または転送前の重要な情報の不適切な削除(CWE-212)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"214": {
		CweID:               "214",
		Name:                "重要な情報を使用しているプロセスの呼び出し(CWE-214)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"216": {
		CweID:               "216",
		Name:                "コンテナエラー(CWE-216)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"22": {
		CweID:               "22",
		Name:                "パス・トラバーサル(CWE-22)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"228": {
		CweID:               "228",
		Name:                "不正な構文構造の不適切な処理(CWE-228)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"23": {
		CweID:               "23",
		Name:                "相対パストラバーサル(CWE-23)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"240": {
		CweID:               "240",
		Name:                "一貫性のない構造要素の不適切な処理(CWE-240)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"242": {
		CweID:               "242",
		Name:                "本質的に危険な機能の使用(CWE-242)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"248": {
		CweID:               "248",
		Name:                "キャッチされない例外(CWE-248)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"250": {
		CweID:               "250",
		Name:                "不要な特権による実行(CWE-250)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"252": {
		CweID:               "252",
		Name:                "未チェックの戻り値(CWE-252)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"254": {
		CweID:               "254",
		Name:                "セキュリティ機能(CWE-254)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"255": {
		CweID:               "255",
		Name:                "証明書・パスワードの管理(CWE-255)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"256": {
		CweID:               "256",
		Name:                "認証情報の平文保存(CWE-256)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"257": {
		CweID:               "257",
		Name:                "復元可能な形式でのパスワード保存(CWE-257)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"259": {
		CweID:               "259",
		Name:                "ハードコードされたパスワードの使用(CWE-259)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"260": {
		CweID:               "260",
		Name:                "設定ファイル内のパスワード(CWE-260)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"261": {
		CweID:               "261",
		Name:                "パスワードの弱い暗号の使用(CWE-261)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"264": {
		CweID:               "264",
		Name:                "認可・権限・アクセス制御(CWE-264)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"266": {
		CweID:               "266",
		Name:                "不適切な権限設定(CWE-266)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"269": {
		CweID:               "269",
		Name:                "不適切な権限管理(CWE-269)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"270": {
		CweID:               "270",
		Name:                "特権コンテキストの切り替えエラー(CWE-270)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"271": {
		CweID:               "271",
		Name:                "特権の削除/エラーの低下(CWE-271)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"273": {
		CweID:               "273",
		Name:                "削除された特権に対する不適切なチェック(CWE-273)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"275": {
		CweID:               "275",
		Name:                "パーミッションの問題(CWE-275)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"276": {
		CweID:               "276",
		Name:                "不適切なデフォルトパーミッション(CWE-276)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"279": {
		CweID:               "279",
		Name:                "割り当てられたパーミッションの不適切な実行(CWE-279)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"281": {
		CweID:               "281",
		Name:                "パーミッションの不適切な保持(CWE-281)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"283": {
		CweID:               "283",
		Name:                "未検証の所有権(CWE-283)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"284": {
		CweID:               "284",
		Name:                "不適切なアクセス制御(CWE-284)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"285": {
		CweID:               "285",
		Name:                "不適切な認可(CWE-285)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"287": {
		CweID:               "287",
		Name:                "不適切な認証(CWE-287)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"288": {
		CweID:               "288",
		Name:                "代替パスまたはチャネルを使用した認証回避(CWE-288)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"290": {
		CweID:               "290",
		Name:                "スプーフィングによる認証回避(CWE-290)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"294": {
		CweID:               "294",
		Name:                "Capture-replay による認証回避(CWE-294)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"295": {
		CweID:               "295",
		Name:                "不正な証明書検証(CWE-295)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"297": {
		CweID:               "297",
		Name:                "ホストの不一致による証明書の不適切な検証(CWE-297)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"299": {
		CweID:               "299",
		Name:                "証明書失効の不適切なチェック(CWE-299)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"300": {
		CweID:               "300",
		Name:                "中間者の問題(CWE-300)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"302": {
		CweID:               "302",
		Name:                "認証回避の脆弱性(CWE-302)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"303": {
		CweID:               "303",
		Name:                "認証アルゴリズムの不適切な実装(CWE-303)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"304": {
		CweID:               "304",
		Name:                "認証の重要なステップの欠如(CWE-304)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"305": {
		CweID:               "305",
		Name:                "根本の脆弱性による認証回避(CWE-305)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"306": {
		CweID:               "306",
		Name:                "重要な機能に対する認証の欠如(CWE-306)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"307": {
		CweID:               "307",
		Name:                "過度な認証試行の不適切な制限(CWE-307)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"310": {
		CweID:               "310",
		Name:                "暗号の問題(CWE-310)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"311": {
		CweID:               "311",
		Name:                "重要なデータの暗号化の欠如(CWE-311)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"312": {
		CweID:               "312",
		Name:                "重要な情報の平文保存(CWE-312)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"315": {
		CweID:               "315",
		Name:                "Cookie における重要な情報の平文保存(CWE-315)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"316": {
		CweID:               "316",
		Name:                "メモリにおける平文での重要な情報の保存(CWE-316)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"319": {
		CweID:               "319",
		Name:                "重要な情報の平文での送信(CWE-319)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"320": {
		CweID:               "320",
		Name:                "鍵管理のエラー(CWE-320)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"321": {
		CweID:               "321",
		Name:                "ハードコードされた暗号鍵の使用(CWE-321)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"322": {
		CweID:               "322",
		Name:                "エンティティ認証のない鍵交換(CWE-322)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"325": {
		CweID:               "325",
		Name:                "暗号化処理の不備(CWE-325)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"326": {
		CweID:               "326",
		Name:                "不適切な暗号強度(CWE-326)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"327": {
		CweID:               "327",
		Name:                "不完全、または危険な暗号アルゴリズムの使用(CWE-327)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"328": {
		CweID:               "328",
		Name:                "脆弱なハッシュの使用(CWE-328)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"329": {
		CweID:               "329",
		Name:                "CBC モードにおけるランダムな初期化ベクトルの不使用(CWE-329)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"330": {
		CweID:               "330",
		Name:                "不十分なランダム値の使用(CWE-330)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"331": {
		CweID:               "331",
		Name:                "エントロピー不足(CWE-331)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"332": {
		CweID:               "332",
		Name:                "PRNG における不十分なエントロピー(CWE-332)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"334": {
		CweID:               "334",
		Name:                "不十分なランダム値(CWE-334)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"335": {
		CweID:               "335",
		Name:                "PRNG におけるシードの不正な使用(CWE-335)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"338": {
		CweID:               "338",
		Name:                "暗号における脆弱な PRNG の使用(CWE-338)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"345": {
		CweID:               "345",
		Name:                "データの信頼性についての不十分な検証(CWE-345)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"346": {
		CweID:               "346",
		Name:                "同一生成元ポリシー違反(CWE-346)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"347": {
		CweID:               "347",
		Name:                "デジタル署名の不適切な検証(CWE-347)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"349": {
		CweID:               "349",
		Name:                "信頼できるデータ受け入れ時の信頼できない無関係なデータの受け入れ(CWE-349)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"35": {
		CweID:               "35",
		Name:                "パストラバーサル(CWE-35)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"350": {
		CweID:               "350",
		Name:                "セキュリティ上重要なアクションのための逆引き DNS への依存(CWE-350)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"352": {
		CweID:               "352",
		Name:                "クロスサイトリクエストフォージェリ(CWE-352)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"353": {
		CweID:               "353",
		Name:                "完全性チェックの欠如(CWE-353)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"354": {
		CweID:               "354",
		Name:                "データの整合性検証不備(CWE-354)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"357": {
		CweID:               "357",
		Name:                "危険な操作に対する不十分な警告(CWE-357)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"358": {
		CweID:               "358",
		Name:                "不適切に実装されたセキュリティチェック(CWE-358)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"359": {
		CweID:               "359",
		Name:                "認可されていない行為者への個人情報の漏えい(CWE-359)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"36": {
		CweID:               "36",
		Name:                "絶対パストラバーサル(CWE-36)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"361": {
		CweID:               "361",
		Name:                "時間とステータス(CWE-361)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"362": {
		CweID:               "362",
		Name:                "競合状態(CWE-362)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"364": {
		CweID:               "364",
		Name:                "シグナルハンドラの競合状態(CWE-364)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"367": {
		CweID:               "367",
		Name:                "Time-of-check Time-of-use (TOCTOU) 競合状態(CWE-367)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"369": {
		CweID:               "369",
		Name:                "ゼロ除算(CWE-369)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"371": {
		CweID:               "371",
		Name:                "状態の問題(CWE-371)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"377": {
		CweID:               "377",
		Name:                "安全でない一時ファイル(CWE-377)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"378": {
		CweID:               "378",
		Name:                "不適切なアクセスパーミションでの一時ファイル作成(CWE-378)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"379": {
		CweID:               "379",
		Name:                "不適切なアクセスパーミションのディレクトリに一時ファイル作成(CWE-379)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"384": {
		CweID:               "384",
		Name:                "セッションの固定化(CWE-384)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"385": {
		CweID:               "385",
		Name:                "秘密のタイミングチャネル(CWE-385)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"388": {
		CweID:               "388",
		Name:                "エラー処理(CWE-388)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"398": {
		CweID:               "398",
		Name:                "コードの品質(CWE-398)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"399": {
		CweID:               "399",
		Name:                "リソース管理の問題(CWE-399)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"400": {
		CweID:               "400",
		Name:                "リソースの枯渇(CWE-400)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"401": {
		CweID:               "401",
		Name:                "有効期限後のメモリの解放の欠如(CWE-401)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"404": {
		CweID:               "404",
		Name:                "リソースの不適切なシャットダウンおよびリリース(CWE-404)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"405": {
		CweID:               "405",
		Name:                "非対称のリソース消費に関する脆弱性(CWE-405)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"406": {
		CweID:               "406",
		Name:                "ネットワークメッセージ量の不十分な制御 (ネットワーク増幅)(CWE-406)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"407": {
		CweID:               "407",
		Name:                "アルゴリズムの複雑性(CWE-407)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"410": {
		CweID:               "410",
		Name:                "不十分なリソースプール(CWE-410)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"412": {
		CweID:               "412",
		Name:                "外部からの操作の制限不備(CWE-412)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"413": {
		CweID:               "413",
		Name:                "不適切なリソースロック(CWE-413)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"415": {
		CweID:               "415",
		Name:                "二重解放(CWE-415)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"416": {
		CweID:               "416",
		Name:                "解放済みメモリの使用(CWE-416)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"417": {
		CweID:               "417",
		Name:                "チャネルおよびパスのエラー(CWE-417)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"425": {
		CweID:               "425",
		Name:                "リクエストの直接送信(CWE-425)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"426": {
		CweID:               "426",
		Name:                "信頼できない検索パス(CWE-426)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"427": {
		CweID:               "427",
		Name:                "制御されていない検索パスの要素(CWE-427)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"428": {
		CweID:               "428",
		Name:                "引用されない検索パスまたは要素(CWE-428)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"434": {
		CweID:               "434",
		Name:                "危険なタイプのファイルの無制限アップロード(CWE-434)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"435": {
		CweID:               "435",
		Name:                "複数の正しく動作するエンティティ間における不適切な相互作用(CWE-435)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"436": {
		CweID:               "436",
		Name:                "解釈の競合(CWE-436)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"441": {
		CweID:               "441",
		Name:                "フィルタリング回避(CWE-441)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"444": {
		CweID:               "444",
		Name:                "HTTP リクエストスマグリング(CWE-444)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"451": {
		CweID:               "451",
		Name:                "ユーザインターフェースにおける重要情報の誤った表示(CWE-451)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"453": {
		CweID:               "453",
		Name:                "変数の安全ではないデフォルト値への初期化(CWE-453)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"457": {
		CweID:               "457",
		Name:                "初期化されていない変数の使用(CWE-457)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"459": {
		CweID:               "459",
		Name:                "不完全なクリーンアップ(CWE-459)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"470": {
		CweID:               "470",
		Name:                "クラスまたはコードを選択する外部から制御された入力の使用(CWE-470)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"471": {
		CweID:               "471",
		Name:                "不変と仮定されるデータの変更(CWE-471)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"472": {
		CweID:               "472",
		Name:                "不変と仮定される Web パラメータの外部制御(CWE-472)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"476": {
		CweID:               "476",
		Name:                "NULL ポインタデリファレンス(CWE-476)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"485": {
		CweID:               "485",
		Name:                "不十分なカプセル化(CWE-485)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"489": {
		CweID:               "489",
		Name:                "アクティブ状態のデバッグコード(CWE-489)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"494": {
		CweID:               "494",
		Name:                "ダウンロードしたコードの完全性検証不備(CWE-494)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"497": {
		CweID:               "497",
		Name:                "認可されていない制御領域への重要情報の漏えい(CWE-497)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"502": {
		CweID:               "502",
		Name:                "信頼できないデータのデシリアライゼーション(CWE-502)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"506": {
		CweID:               "506",
		Name:                "埋め込まれた悪意のあるコード(CWE-506)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"507": {
		CweID:               "507",
		Name:                "トロイの木馬(CWE-507)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"521": {
		CweID:               "521",
		Name:                "脆弱なパスワードの要求(CWE-521)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"522": {
		CweID:               "522",
		Name:                "認証情報の不十分な保護(CWE-522)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"523": {
		CweID:               "523",
		Name:                "認証情報の保護しない転送(CWE-523)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"527": {
		CweID:               "527",
		Name:                "認可されていない制御領域へのバージョン管理リポジトリの漏えい(CWE-527)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"532": {
		CweID:               "532",
		Name:                "ログファイルからの情報漏えい(CWE-532)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"534": {
		CweID:               "534",
		Name:                "デバッグログファイルからの情報漏えい(CWE-534)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"538": {
		CweID:               "538",
		Name:                "ファイルおよびディレクトリ情報の漏えい(CWE-538)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"539": {
		CweID:               "539",
		Name:                "重要情報を含む永続 Cookie の使用(CWE-539)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"540": {
		CweID:               "540",
		Name:                "重要な情報を含むソースコード(CWE-540)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"548": {
		CweID:               "548",
		Name:                "ディレクトリリスティングによる情報漏えい(CWE-548)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"552": {
		CweID:               "552",
		Name:                "外部からアクセス可能なファイルまたはディレクトリ(CWE-552)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"565": {
		CweID:               "565",
		Name:                "検証および完全性チェックを行っていない Cookie への依存(CWE-565)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"567": {
		CweID:               "567",
		Name:                "マルチスレッドコンテキスト内の共有データへの非同期アクセス(CWE-567)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"573": {
		CweID:               "573",
		Name:                "呼び出し元による仕様の不適切な準拠(CWE-573)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"59": {
		CweID:               "59",
		Name:                "リンク解釈の問題(CWE-59)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"590": {
		CweID:               "590",
		Name:                "ヒープ領域の不適切な解放(CWE-590)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"598": {
		CweID:               "598",
		Name:                "GET リクエストにおけるクエリ文字列からの情報漏えい(CWE-598)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"601": {
		CweID:               "601",
		Name:                "オープンリダイレクト(CWE-601)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"602": {
		CweID:               "602",
		Name:                "サーバ側のセキュリティのクライアント側での実施(CWE-602)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"603": {
		CweID:               "603",
		Name:                "クライアント側認証の使用(CWE-603)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"605": {
		CweID:               "605",
		Name:                "同一ポートに複数のソケットをバインドする問題(CWE-605)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"61": {
		CweID:               "61",
		Name:                "UNIX Symbolic Link のフォロー(CWE-61)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"610": {
		CweID:               "610",
		Name:                "別領域リソースに対する外部からの制御可能な参照(CWE-610)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"611": {
		CweID:               "611",
		Name:                "XML 外部エンティティ参照の不適切な制限(CWE-611)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"613": {
		CweID:               "613",
		Name:                "不適切なセッション期限(CWE-613)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"617": {
		CweID:               "617",
		Name:                "到達可能なアサーション(CWE-617)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"620": {
		CweID:               "620",
		Name:                "未検証のパスワード変更(CWE-620)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"639": {
		CweID:               "639",
		Name:                "ユーザ制御の鍵による認証回避(CWE-639)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"64": {
		CweID:               "64",
		Name:                "Windows ショートカットのフォロー(CWE-64)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"640": {
		CweID:               "640",
		Name:                "パスワードを忘れた場合の脆弱なパスワードリカバリの仕組み(CWE-640)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"641": {
		CweID:               "641",
		Name:                "ファイルおよびその他のリソース名の不適切な制限(CWE-641)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"642": {
		CweID:               "642",
		Name:                "重要な状態データの外部制御(CWE-642)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"643": {
		CweID:               "643",
		Name:                "Xpath インジェクション(CWE-643)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"644": {
		CweID:               "644",
		Name:                "HTTP ヘッダのスクリプト構文の不適切な無効化(CWE-644)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"645": {
		CweID:               "645",
		Name:                "過度に制限されたアカウントロックアウトメカニズム(CWE-645)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"649": {
		CweID:               "649",
		Name:                "完全性チェックなしのセキュリティ関連の入力の難読化または暗号化への依存(CWE-649)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"657": {
		CweID:               "657",
		Name:                "セキュリティ設計の原則に反した設計(CWE-657)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"662": {
		CweID:               "662",
		Name:                "不適切な同期(CWE-662)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"664": {
		CweID:               "664",
		Name:                "ライフタイムを通してのリソースの不適切な制御(CWE-664)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"665": {
		CweID:               "665",
		Name:                "不適切な初期化(CWE-665)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"667": {
		CweID:               "667",
		Name:                "不適切なロック(CWE-667)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"668": {
		CweID:               "668",
		Name:                "誤った領域へのリソースの漏えい(CWE-668)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"669": {
		CweID:               "669",
		Name:                "領域間での誤ったリソース移動(CWE-669)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"670": {
		CweID:               "670",
		Name:                "常に不適切な制御フローの実装(CWE-670)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"672": {
		CweID:               "672",
		Name:                "有効期限後または解放後のリソースの操作(CWE-672)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"674": {
		CweID:               "674",
		Name:                "不適切な再帰制御(CWE-674)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"676": {
		CweID:               "676",
		Name:                "潜在的に危険な関数の使用(CWE-676)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"681": {
		CweID:               "681",
		Name:                "数値型間の変換の誤り(CWE-681)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"682": {
		CweID:               "682",
		Name:                "計算の誤り(CWE-682)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"688": {
		CweID:               "688",
		Name:                "引数として誤った変数または参照を使用した関数呼び出し(CWE-688)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"693": {
		CweID:               "693",
		Name:                "保護メカニズムの不具合(CWE-693)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"694": {
		CweID:               "694",
		Name:                "競合する識別子を使用した複数のリソースの使用(CWE-694)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"697": {
		CweID:               "697",
		Name:                "不適切な比較(CWE-697)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"703": {
		CweID:               "703",
		Name:                "例外的な状況に対する不適切なチェックまたは処理(CWE-703)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"704": {
		CweID:               "704",
		Name:                "不正な型変換またはキャスト(CWE-704)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"706": {
		CweID:               "706",
		Name:                "誤って解決された名前や参照の使用(CWE-706)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"707": {
		CweID:               "707",
		Name:                "不適切な無害化(CWE-707)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"710": {
		CweID:               "710",
		Name:                "コーディング標準の不適切な順守(CWE-710)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"73": {
		CweID:               "73",
		Name:                "ファイル名やパス名の外部制御(CWE-73)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"732": {
		CweID:               "732",
		Name:                "重要なリソースに対する不適切なパーミッションの割り当て(CWE-732)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"74": {
		CweID:               "74",
		Name:                "インジェクション(CWE-74)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"749": {
		CweID:               "749",
		Name:                "危険なメソッドや機能の公開(CWE-749)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"75": {
		CweID:               "75",
		Name:                "特殊要素の不適切なサニタイジング(CWE-75)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"754": {
		CweID:               "754",
		Name:                "例外的な状態における不適切なチェック(CWE-754)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"755": {
		CweID:               "755",
		Name:                "例外的な状態における不適切な処理(CWE-755)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"757": {
		CweID:               "757",
		Name:                "アルゴリズムのダウングレード(CWE-757)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"759": {
		CweID:               "759",
		Name:                "Salt を使用しない一方向ハッシュの使用(CWE-759)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"760": {
		CweID:               "760",
		Name:                "予測可能な Salt の一方向ハッシュの使用(CWE-760)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"763": {
		CweID:               "763",
		Name:                "無効なポインタや参照の解放(CWE-763)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"769": {
		CweID:               "769",
		Name:                "ファイル記述子の枯渇(CWE-769)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"77": {
		CweID:               "77",
		Name:                "コマンドインジェクション(CWE-77)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"770": {
		CweID:               "770",
		Name:                "制限またはスロットリング無しのリソースの割り当て(CWE-770)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"772": {
		CweID:               "772",
		Name:                "有効なライフタイム後のリソースの解放の欠如(CWE-772)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"774": {
		CweID:               "774",
		Name:                "制限またはスロットリング無しのファイル記述子またはハンドルの割り当て(CWE-774)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"775": {
		CweID:               "775",
		Name:                "有効期限後のファイル記述子またはハンドルの解放の欠如(CWE-775)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"776": {
		CweID:               "776",
		Name:                "DTD の再帰的なエンティティ参照の不適切な制限(CWE-776)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"78": {
		CweID:               "78",
		Name:                "OSコマンドインジェクション(CWE-78)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"787": {
		CweID:               "787",
		Name:                "境界外書き込み(CWE-787)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"788": {
		CweID:               "788",
		Name:                "バッファの終端後のメモリ領域に対するアクセス(CWE-788)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"789": {
		CweID:               "789",
		Name:                "過剰なサイズ値のメモリ割り当て(CWE-789)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"79": {
		CweID:               "79",
		Name:                "クロスサイトスクリプティング(CWE-79)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"798": {
		CweID:               "798",
		Name:                "ハードコードされた認証情報の使用(CWE-798)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"799": {
		CweID:               "799",
		Name:                "インタラクション頻度の不適切な制御(CWE-799)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"80": {
		CweID:               "80",
		Name:                "クロスサイトスクリプティング (Basic XSS)(CWE-80)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"805": {
		CweID:               "805",
		Name:                "不適切な長さの値によるバッファへのアクセス(CWE-805)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"807": {
		CweID:               "807",
		Name:                "セキュリティ決定の信頼できない入力への依存(CWE-807)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"820": {
		CweID:               "820",
		Name:                "同期の欠如(CWE-820)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"821": {
		CweID:               "821",
		Name:                "不正な同期(CWE-821)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"822": {
		CweID:               "822",
		Name:                "信頼できないポインタデリファレンス(CWE-822)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"823": {
		CweID:               "823",
		Name:                "範囲外のポインタオフセットの使用(CWE-823)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"824": {
		CweID:               "824",
		Name:                "初期化されていないポインタのアクセス(CWE-824)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"829": {
		CweID:               "829",
		Name:                "信頼できない制御領域からの機能の組み込み(CWE-829)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"834": {
		CweID:               "834",
		Name:                "過度なイテレーション(CWE-834)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"835": {
		CweID:               "835",
		Name:                "無限ループ(CWE-835)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"836": {
		CweID:               "836",
		Name:                "パスワードの代わりにパスワードハッシュを使用する認証(CWE-836)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"838": {
		CweID:               "838",
		Name:                "出力コンテキストの不適切なエンコード(CWE-838)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"843": {
		CweID:               "843",
		Name:                "型の取り違え(CWE-843)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"862": {
		CweID:               "862",
		Name:                "認証の欠如(CWE-862)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"863": {
		CweID:               "863",
		Name:                "不正な認証(CWE-863)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"87": {
		CweID:               "87",
		Name:                "代替 XSS 構文の不適切な無効化(CWE-87)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"88": {
		CweID:               "88",
		Name:                "引数の挿入または変更(CWE-88)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"89": {
		CweID:               "89",
		Name:                "SQLインジェクション(CWE-89)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"90": {
		CweID:               "90",
		Name:                "LDAP インジェクション(CWE-90)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"908": {
		CweID:               "908",
		Name:                "初期化されていないリソースの使用(CWE-908)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"909": {
		CweID:               "909",
		Name:                "リソースの初期化の不備(CWE-909)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"91": {
		CweID:               "91",
		Name:                "ブラインド XPath インジェクション(CWE-91)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"912": {
		CweID:               "912",
		Name:                "非公開の機能(CWE-912)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"913": {
		CweID:               "913",
		Name:                "動的に操作されるコードリソースの不適切な制御(CWE-913)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"915": {
		CweID:               "915",
		Name:                "動的に決定されたオブジェクト属性の不適切に制御された変更(CWE-915)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"916": {
		CweID:               "916",
		Name:                "強度が不十分なパスワードハッシュの使用(CWE-916)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"917": {
		CweID:               "917",
		Name:                "言語構文の表現に使用される特殊な要素の不適切な無効化(CWE-917)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"918": {
		CweID:               "918",
		Name:                "サーバサイドのリクエストフォージェリ(CWE-918)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"920": {
		CweID:               "920",
		Name:                "消費電力の不適切な制限(CWE-920)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"921": {
		CweID:               "921",
		Name:                "アクセス制御のないメカニズムでの重要データの保存(CWE-921)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"922": {
		CweID:               "922",
		Name:                "重要な情報のセキュアでない格納(CWE-922)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"924": {
		CweID:               "924",
		Name:                "通信チャネルで送信中のメッセージの整合性への不適切な強制(CWE-924)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"93": {
		CweID:               "93",
		Name:                "CRLF インジェクション(CWE-93)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"94": {
		CweID:               "94",
		Name:                "コード・インジェクション(CWE-94)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"943": {
		CweID:               "943",
		Name:                "データクエリロジックの特殊要素の不適切な中立化(CWE-943)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"96": {
		CweID:               "96",
		Name:                "静的に保存されたコード内のディレクティブの不適切な無効化(CWE-96)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"98": {
		CweID:               "98",
		Name:                "PHP リモートファイルインクルージョン(CWE-98)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"99": {
		CweID:               "99",
		Name:                "リソースの挿入(CWE-99)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"DesignError": {
		CweID:               "DesignError",
		Name:                "設計上の問題(CWE-DesignError)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"Other": {
		CweID:               "Other",
		Name:                "その他(CWE-Other)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"nocwe": {
		CweID:               "nocwe",
		Name:                "CWE以外(CWE-nocwe)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
	"noinfo": {
		CweID:               "noinfo",
		Name:                "情報不足(CWE-noinfo)",
		Description:         "",
		ExtendedDescription: "",
		Lang:                "ja",
	},
}
