[cveDict]
  Type = "sqlite3"
  SQLite3Path = "/home/ubuntu/vulsctl/docker/cve.sqlite3"

[ovalDict]
  Type = "sqlite3"
  SQLite3Path = "/home/ubuntu/vulsctl/docker/oval.sqlite3"

[gost]
  Type = "sqlite3"
  SQLite3Path = "/home/ubuntu/vulsctl/docker/gost.sqlite3"

[exploit]
  Type = "sqlite3"
  SQLite3Path = "/home/ubuntu/vulsctl/docker/go-exploitdb.sqlite3"

[metasploit]
  type = "sqlite3"
  SQLite3Path = "/home/ubuntu/vulsctl/docker/go-msfdb.sqlite3"

[default]

[servers]

[servers.cpe_version_match]
type = "pseudo"
cpeNames = [ "cpe:/a:rubyonrails:rails:3.0.1" ]

[servers.nvd_vendor_product_match]
 type = "pseudo"
 cpeNames = [ "cpe:/a:djangoproject:django" ]

[servers.cpe_version_match_no_jvn]
type = "pseudo"
cpeNames = [ "cpe:/a:apache:tomcat:7.0.27" ]

[servers.jvn_vendor_product_match]
type = "pseudo"
cpeNames = [ "cpe:/a:hitachi_abb_power_grids:afs660:1.0.0" ]

[servers.jvn_vendor_product_match_no_version]
type = "pseudo"
cpeNames = [ "cpe:/o:nec:aterm_wg2600hp2_firmware"]

[servers.gemfile]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/Gemfile.lock"]

[servers.pipfile]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/Pipfile.lock"]

[servers.poetry]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/poetry.lock"]

[servers.composer]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/composer.lock"]

[servers.packagelock]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/package-lock.json"]

[servers.yarn]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/yarn.lock"]

[servers.cargo]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/Cargo.lock"]

[servers.gomod]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/go.sum"]

