package alert

// AlertDictUS has USCERT alerts
var AlertDictUS = map[string][]Alert{
	"CVE-1999-0532": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-103A",
		Title: `DNS Zone Transfer AXFR Requests May Leak Domain Information`,
		Team:  "us",
	},
	},
	"CVE-2006-3227": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2008-0015": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA09-195A",
		Title: `Microsoft Updates for Multiple Vulnerabilities`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA09-209A",
		Title: `Microsoft Windows, Internet Explorer, and Active Template Library (ATL) Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2008-2244": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2009-0658": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA09-051A",
		Title: `Adobe Acrobat and Reader Vulnerability`,
		Team:  "us",
	},
	},
	"CVE-2009-0927": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA13-141A",
		Title: `Washington, DC Radio Station Web Site Compromises`,
		Team:  "us",
	},
	},
	"CVE-2009-1492": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA09-133B",
		Title: `Adobe Reader and Acrobat JavaScript Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2009-1493": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA09-133B",
		Title: `Adobe Reader and Acrobat JavaScript Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2009-1537": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA09-195A",
		Title: `Microsoft Updates for Multiple Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2009-3103": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA17-181A",
		Title: `Petya Ransomware `,
		Team:  "us",
	},
	},
	"CVE-2009-3129": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2009-3674": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2009-3953": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2010-0018": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA10-012B",
		Title: `Microsoft Windows EOT Font and Adobe Flash Player 6 Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2010-0188": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA13-141A",
		Title: `Washington, DC Radio Station Web Site Compromises`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA14-300A",
		Title: `Phishing Campaign Linked with “Dyre” Banking Malware`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2010-0806": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2010-1297": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA10-162A",
		Title: `Adobe Flash and AIR Vulnerabilities`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA10-159A",
		Title: `Adobe Flash, Reader, and Acrobat Vulnerability`,
		Team:  "us",
	},
	},
	"CVE-2010-2883": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2010-3333": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2011-0101": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2011-0611": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2011-2462": {{
		URL:   "https://www.jpcert.or.jp/at/2011/at110034.html",
		Title: `Adobe Reader 及び Acrobat の脆弱性に関する注意喚起`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2012-0158": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2012-1723": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2012-1856": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2012-1889": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA12-174A",
		Title: `Microsoft XML Core Services Attack Activity`,
		Team:  "us",
	},
	},
	"CVE-2012-3174": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA13-010A",
		Title: `Oracle Java 7 Security Manager Bypass Vulnerability`,
		Team:  "us",
	},
	},
	"CVE-2012-4681": {{
		URL:   "https://www.jpcert.or.jp/at/2012/at120028.html",
		Title: `2012年 8月 Java SE の脆弱性に関する注意喚起`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA12-240A",
		Title: `Oracle Java 7 Security Manager Bypass Vulnerability`,
		Team:  "us",
	},
	},
	"CVE-2012-4792": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA13-015A",
		Title: `Microsoft Releases Update for Internet Explorer Vulnerability CVE-2012-4792`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2013-0074": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2013-0140": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA13-193A",
		Title: `Exploit Tool Targets Vulnerabilities in McAfee ePolicy Orchestrator (ePO)`,
		Team:  "us",
	},
	},
	"CVE-2013-0141": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA13-193A",
		Title: `Exploit Tool Targets Vulnerabilities in McAfee ePolicy Orchestrator (ePO)`,
		Team:  "us",
	},
	},
	"CVE-2013-0422": {{
		URL:   "https://www.jpcert.or.jp/at/2013/at130004.html",
		Title: `Oracle Java SE のクリティカルパッチアップデートに関する注意喚起`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA13-141A",
		Title: `Washington, DC Radio Station Web Site Compromises`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA13-010A",
		Title: `Oracle Java 7 Security Manager Bypass Vulnerability`,
		Team:  "us",
	},
	},
	"CVE-2013-0625": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2013-0632": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2013-0809": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA13-064A",
		Title: `Oracle Java Contains Multiple Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2013-1347": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2013-1493": {{
		URL:   "https://www.jpcert.or.jp/at/2013/at130014.html",
		Title: `2013年3月 Oracle Java SE のクリティカルパッチアップデートに関する注意喚起`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA13-064A",
		Title: `Oracle Java Contains Multiple Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2013-1571": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA13-169A",
		Title: `Oracle Releases Updates for Javadoc and Other Java SE Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2013-2465": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2013-2729": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA14-300A",
		Title: `Phishing Campaign Linked with “Dyre” Banking Malware`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2013-3336": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2013-5211": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA14-017A",
		Title: `UDP-Based Amplification Attacks`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA14-013A",
		Title: `NTP Amplification Attacks Using CVE-2013-5211`,
		Team:  "us",
	},
	},
	"CVE-2013-5326": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2014-0160": {{
		URL:   "https://www.jpcert.or.jp/at/2014/at140013.html",
		Title: `OpenSSL の脆弱性に関する注意喚起`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA14-098A",
		Title: `OpenSSL &#039;Heartbleed&#039; vulnerability (CVE-2014-0160)`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2014-0322": {{
		URL:   "https://www.jpcert.or.jp/at/2014/at140009.html",
		Title: `2014年2月 Microsoft Internet Explorer の未修正の脆弱性に関する注意喚起`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2014-0564": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2014-1761": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2014-1776": {{
		URL:   "https://www.jpcert.or.jp/at/2014/at140018.html",
		Title: `2014年4月 Microsoft Internet Explorer の未修正の脆弱性に関する注意喚起`,
		Team:  "us",
	}, {
		URL:   "https://www.jpcert.or.jp/at/2014/at140020.html",
		Title: `マイクロソフト セキュリティ情報(MS14-021)に関する注意喚起`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2014-3393": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA16-250A",
		Title: `The Increasing Threat to Network Infrastructure Devices and Recommended Mitigations`,
		Team:  "us",
	},
	},
	"CVE-2014-3566": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA14-290A",
		Title: `SSL 3.0 Protocol Vulnerability and POODLE Attack`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-120A",
		Title: `Securing End-to-End Communications`,
		Team:  "us",
	},
	},
	"CVE-2014-4114": {{
		URL:   "https://www.jpcert.or.jp/at/2014/at140039.html",
		Title: `2014年10月 Microsoft セキュリティ情報 (緊急 3件含) に関する注意喚起`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-119A",
		Title: `Top 30 Targeted High Risk Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2014-6271": {{
		URL:   "https://www.jpcert.or.jp/at/2014/at140037.html",
		Title: `GNU bash の脆弱性に関する注意喚起`,
		Team:  "us",
	}, {
		URL:   "https://www.jpcert.or.jp/at/2014/at140038.html",
		Title: `TCP 10000番ポートへのスキャンの増加に関する注意喚起`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA14-268A",
		Title: `GNU Bourne-Again Shell (Bash) ‘Shellshock’ Vulnerability (CVE-2014-6271, CVE-2014-7169, CVE-2014-7186, CVE-2014-7187, CVE-2014-6277 and CVE 2014-6278) `,
		Team:  "us",
	},
	},
	"CVE-2014-6277": {{
		URL:   "https://www.jpcert.or.jp/at/2014/at140037.html",
		Title: `GNU bash の脆弱性に関する注意喚起`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA14-268A",
		Title: `GNU Bourne-Again Shell (Bash) ‘Shellshock’ Vulnerability (CVE-2014-6271, CVE-2014-7169, CVE-2014-7186, CVE-2014-7187, CVE-2014-6277 and CVE 2014-6278) `,
		Team:  "us",
	},
	},
	"CVE-2014-6278": {{
		URL:   "https://www.jpcert.or.jp/at/2014/at140037.html",
		Title: `GNU bash の脆弱性に関する注意喚起`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA14-268A",
		Title: `GNU Bourne-Again Shell (Bash) ‘Shellshock’ Vulnerability (CVE-2014-6271, CVE-2014-7169, CVE-2014-7186, CVE-2014-7187, CVE-2014-6277 and CVE 2014-6278) `,
		Team:  "us",
	},
	},
	"CVE-2014-6321": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA14-318A",
		Title: `Microsoft Secure Channel (Schannel) Vulnerability (CVE-2014-6321) `,
		Team:  "us",
	},
	},
	"CVE-2014-6332": {{
		URL:   "https://www.jpcert.or.jp/at/2015/at150015.html",
		Title: `ランサムウエア感染に関する注意喚起`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA14-318B",
		Title: `Microsoft Windows OLE Automation Array Remote Code Execution Vulnerability `,
		Team:  "us",
	},
	},
	"CVE-2014-7169": {{
		URL:   "https://www.jpcert.or.jp/at/2014/at140037.html",
		Title: `GNU bash の脆弱性に関する注意喚起`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA14-268A",
		Title: `GNU Bourne-Again Shell (Bash) ‘Shellshock’ Vulnerability (CVE-2014-6271, CVE-2014-7169, CVE-2014-7186, CVE-2014-7187, CVE-2014-6277 and CVE 2014-6278) `,
		Team:  "us",
	},
	},
	"CVE-2014-7186": {{
		URL:   "https://www.jpcert.or.jp/at/2014/at140037.html",
		Title: `GNU bash の脆弱性に関する注意喚起`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA14-268A",
		Title: `GNU Bourne-Again Shell (Bash) ‘Shellshock’ Vulnerability (CVE-2014-6271, CVE-2014-7169, CVE-2014-7186, CVE-2014-7187, CVE-2014-6277 and CVE 2014-6278) `,
		Team:  "us",
	},
	},
	"CVE-2014-7187": {{
		URL:   "https://www.jpcert.or.jp/at/2014/at140037.html",
		Title: `GNU bash の脆弱性に関する注意喚起`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA14-268A",
		Title: `GNU Bourne-Again Shell (Bash) ‘Shellshock’ Vulnerability (CVE-2014-6271, CVE-2014-7169, CVE-2014-7186, CVE-2014-7187, CVE-2014-6277 and CVE 2014-6278) `,
		Team:  "us",
	},
	},
	"CVE-2014-8730": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA14-290A",
		Title: `SSL 3.0 Protocol Vulnerability and POODLE Attack`,
		Team:  "us",
	},
	},
	"CVE-2015-2387": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-195A",
		Title: `Adobe Flash and Microsoft Windows Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2015-5119": {{
		URL:   "https://www.jpcert.or.jp/at/2015/at150019.html",
		Title: `Adobe Flash Player の脆弱性 (APSB15-16) に関する注意喚起`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-195A",
		Title: `Adobe Flash and Microsoft Windows Vulnerabilities`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-213A",
		Title: `Recent Email Phishing Campaigns – Mitigation and Response Recommendations`,
		Team:  "us",
	},
	},
	"CVE-2015-5122": {{
		URL:   "https://www.jpcert.or.jp/at/2015/at150020.html",
		Title: `2015年7月 Adobe Flash Player の未修正の脆弱性に関する注意喚起`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-195A",
		Title: `Adobe Flash and Microsoft Windows Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2015-5123": {{
		URL:   "https://www.jpcert.or.jp/at/2015/at150020.html",
		Title: `2015年7月 Adobe Flash Player の未修正の脆弱性に関する注意喚起`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA15-195A",
		Title: `Adobe Flash and Microsoft Windows Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2015-6585": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA17-164A",
		Title: `HIDDEN COBRA – North Korea’s DDoS Botnet Infrastructure`,
		Team:  "us",
	},
	},
	"CVE-2015-8651": {{
		URL:   "https://www.jpcert.or.jp/at/2016/at160001.html",
		Title: `Adobe Flash Player の脆弱性 (APSB16-01) に関する注意喚起`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA17-164A",
		Title: `HIDDEN COBRA – North Korea’s DDoS Botnet Infrastructure`,
		Team:  "us",
	},
	},
	"CVE-2016-0034": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA17-164A",
		Title: `HIDDEN COBRA – North Korea’s DDoS Botnet Infrastructure`,
		Team:  "us",
	},
	},
	"CVE-2016-1019": {{
		URL:   "https://www.jpcert.or.jp/at/2016/at160016.html",
		Title: `Adobe Flash Player の脆弱性 (APSB16-10) に関する注意喚起`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA17-164A",
		Title: `HIDDEN COBRA – North Korea’s DDoS Botnet Infrastructure`,
		Team:  "us",
	},
	},
	"CVE-2016-2207": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA16-187A",
		Title: `Symantec and Norton Security Products Contain Critical Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2016-2208": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA16-187A",
		Title: `Symantec and Norton Security Products Contain Critical Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2016-2209": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA16-187A",
		Title: `Symantec and Norton Security Products Contain Critical Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2016-2210": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA16-187A",
		Title: `Symantec and Norton Security Products Contain Critical Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2016-2211": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA16-187A",
		Title: `Symantec and Norton Security Products Contain Critical Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2016-3644": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA16-187A",
		Title: `Symantec and Norton Security Products Contain Critical Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2016-3645": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA16-187A",
		Title: `Symantec and Norton Security Products Contain Critical Vulnerabilities`,
		Team:  "us",
	},
	},
	"CVE-2016-4117": {{
		URL:   "https://www.jpcert.or.jp/at/2016/at160024.html",
		Title: `Adobe Flash Player の脆弱性 (APSB16-15) に関する注意喚起`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA17-164A",
		Title: `HIDDEN COBRA – North Korea’s DDoS Botnet Infrastructure`,
		Team:  "us",
	},
	},
	"CVE-2016-6366": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA16-250A",
		Title: `The Increasing Threat to Network Infrastructure Devices and Recommended Mitigations`,
		Team:  "us",
	},
	},
	"CVE-2016-6367": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA16-250A",
		Title: `The Increasing Threat to Network Infrastructure Devices and Recommended Mitigations`,
		Team:  "us",
	},
	},
	"CVE-2016-6415": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA16-250A",
		Title: `The Increasing Threat to Network Infrastructure Devices and Recommended Mitigations`,
		Team:  "us",
	},
	},
	"CVE-2016-6909": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA16-250A",
		Title: `The Increasing Threat to Network Infrastructure Devices and Recommended Mitigations`,
		Team:  "us",
	},
	},
	"CVE-2016-7089": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA16-250A",
		Title: `The Increasing Threat to Network Infrastructure Devices and Recommended Mitigations`,
		Team:  "us",
	},
	},
	"CVE-2017-0144": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA17-181A",
		Title: `Petya Ransomware `,
		Team:  "us",
	},
	},
	"CVE-2017-0145": {{
		URL:   "https://www.jpcert.or.jp/at/2017/at170020.html",
		Title: `ランサムウエア "WannaCrypt" に関する注意喚起`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA17-181A",
		Title: `Petya Ransomware `,
		Team:  "us",
	},
	},
	"CVE-2017-3066": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/AA18-284A",
		Title: `Publicly Available Tools Seen in Cyber Incidents Worldwide`,
		Team:  "us",
	},
	},
	"CVE-2017-5715": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA18-141A",
		Title: `Side-Channel Vulnerability Variants 3a and 4`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA18-004A",
		Title: `Meltdown and Spectre Side-Channel Vulnerability Guidance`,
		Team:  "us",
	},
	},
	"CVE-2017-5753": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA18-141A",
		Title: `Side-Channel Vulnerability Variants 3a and 4`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA18-004A",
		Title: `Meltdown and Spectre Side-Channel Vulnerability Guidance`,
		Team:  "us",
	},
	},
	"CVE-2017-5754": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA18-141A",
		Title: `Side-Channel Vulnerability Variants 3a and 4`,
		Team:  "us",
	}, {
		URL:   "https://www.us-cert.gov/ncas/alerts/TA18-004A",
		Title: `Meltdown and Spectre Side-Channel Vulnerability Guidance`,
		Team:  "us",
	},
	},
	"CVE-2018-1038": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA18-004A",
		Title: `Meltdown and Spectre Side-Channel Vulnerability Guidance`,
		Team:  "us",
	},
	},
	"CVE-2018-3639": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA18-141A",
		Title: `Side-Channel Vulnerability Variants 3a and 4`,
		Team:  "us",
	},
	},
	"CVE-2018-3640": {{
		URL:   "https://www.us-cert.gov/ncas/alerts/TA18-141A",
		Title: `Side-Channel Vulnerability Variants 3a and 4`,
		Team:  "us",
	},
	},
}
